valor = input('digite algo:')
print('o tipo primitivo é? ',type(valor))
print('tem espaço?', valor.isspace())
print('é um numero?', valor.isnumeric())
print('é escrito?' , valor.isalpha())
print('é alfanumerico?', valor.isalnum())
print('está em maisculo?', valor.isupper())
print('está em minusculo? ', valor.islower())
print('esta capitalizada?', valor.istitle())
